// <auto-generated />
using System;
using FlightBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBooking.Migrations
{
    [DbContext(typeof(BookingsDbContext))]
    [Migration("20220516160742_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBooking.Models.Bookings", b =>
                {
                    b.Property<int>("PnrID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingTime");

                    b.Property<string>("EmailID");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MealsOption");

                    b.Property<int>("NumberOfSeats");

                    b.Property<string>("PassengerAge");

                    b.Property<int>("PassengerID");

                    b.Property<string>("PassengerName");

                    b.Property<string>("SelectedSeatNumbers");

                    b.HasKey("PnrID");

                    b.ToTable("BookingTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
